function [Method,superkingdom,phylum,class,order,family,genus,species,strain] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [METHOD,SUPERKINGDOM,PHYLUM,CLASS1,ORDER,FAMILY,GENUS,SPECIES,STRAIN] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [METHOD,SUPERKINGDOM,PHYLUM,CLASS1,ORDER,FAMILY,GENUS,SPECIES,STRAIN] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Method,superkingdom,phylum,class1,order,family,genus,species,strain] =
%   importfile('CAMI Challenge-CAMI_low_S001-all-L1norm.txt',2, 13);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/04/04 18:40:59

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Method = dataArray{:, 1};
superkingdom = dataArray{:, 2};
phylum = dataArray{:, 3};
class = dataArray{:, 4};
order = dataArray{:, 5};
family = dataArray{:, 6};
genus = dataArray{:, 7};
species = dataArray{:, 8};
strain = dataArray{:, 9};


